### ISSUE TITLE
Change in naming for Launchers Pack

### ISSUE THREAD

**Issue by ericfriesen** [Patrykz94/KSP-RO-Booster-Landing#7]
When I open the craft file it complains about KK.SPX.Merlin1D+, KK.SPX.Merlin1DV+ and fuelTank1-2 missing. 
It looks like the names in the latest launchers pack use underscores in place of periods

**Comment by Patrykz94** [comment]
Did you add the config file I provided? I had this issue and, if I remember correctly, it was because I think RO configs by default remove these parts. The config I provided should fix this hopefully.
Let me know if that helps.

**Comment by Patrykz94** [comment]
Btw. I just published a v1.0.1 of the script. This is just because I forgot to create a release earlier with the new landing logic. If you downloaded the master branch then you already have the new code.
